// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tufefnwqlukamzshkoqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZmVmbndxbHVrYW16c2hrb3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTk3NzUsImV4cCI6MjA2NDk3NTc3NX0.60p5fpkIwpxhGQYM2hX20jQ55pBbbm8aAp5eN5gCy3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);